from pathlib import Path

PROJECT_ROOT = Path(__file__).parent
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
TRAINING_DATA_PATH = DATA_DIR / "training_data.jsonl"
VALIDATION_DATA_PATH = DATA_DIR / "validation_data.jsonl"
OUTPUT_DIR = PROJECT_ROOT / "outputs"
LORA_OUTPUT_DIR = OUTPUT_DIR / "qwen-mermaid-lora"

STUDENT_MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"

MERMAID_MAX_NODES = 8
MERMAID_MIN_NODES = 2
MERMAID_MAX_LABEL_WORDS = 4

TARGET_SAMPLES = 2000
CHECKPOINT_INTERVAL = 50
TRAIN_VAL_SPLIT = 0.9

LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05
LORA_TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj"]

NUM_EPOCHS = 3
LEARNING_RATE = 2e-4
BATCH_SIZE = 4
GRADIENT_ACCUMULATION_STEPS = 4
WARMUP_RATIO = 0.03
WEIGHT_DECAY = 0.01

USE_FP16 = True
USE_BF16 = False
